cargo-features = ["edition2024"]

[package]
name = "extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { path = "../../prost" }

[build-dependencies]
prost-build = { path = "../../prost/prost-build" }