name: Build on Pull Request
on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
    - name: Install musl-tools
      run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Windows
      run: rustup target add i686-pc-windows-gnu && cargo build --verbose --target=x86_64-pc-windows-gnu
    - name: Build Linux
      run: rustup target add x86_64-unknown-linux-gnu && cargo build --verbose --target=x86_64-unknown-linux-gnu
    - name: Run tests on Linux
      run: cargo test --verbose --target=x86_64-unknown-linux-gnu
