name: Build on Pull Request
on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Linux
      run: rustup target add x86_64-unknown-linux-gnu && cargo build --verbose --target=x86_64-unknown-linux-gnu
    - name: Build Windows
      run: rustup target add x86_64-pc-windows-gnu && cargo build --verbose --target=x86_64-pc-windows-gnu
    - name: Run tests on Linux
      run: cargo test --verbose --target=x86_64-unknown-linux-gnu
