name: Release on Push
on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup output dir
        run: mkdir release-out
      - name: Build Linux
        run: rustup target add x86_64-unknown-linux-gnu && cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Move Linux
        run: mv target/x86_64-unknown-linux-gnu/release/eclect release-out/eclect-linux-amd64
      - name: Build Windows
        run: rustup target add x86_64-pc-windows-gnu && cargo build --release --target=x86_64-pc-windows-gnu
      - name: Move Windows
        run: mv target/x86_64-pc-windows-gnu/release/eclect.exe release-out/eclect-windows.exe
      - name: Read crate version
        run: echo RELEASE_TAG=v$(cargo read-manifest | jq .version) >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release-out/*"
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: "true"